version: '3.8'

services:
  mysql:
    build:
      context: ./app_dockerfiles/ubuntu18.04_mysql_server
      dockerfile: Dockerfile
    container_name: mysql_container
    ports:
      - "3306:3306"
    volumes:
      - ./app_data/mysql_db:/var/lib/mysql/db_mlflow
    restart: always

  mlflow:
    build:
      context: ./app_dockerfiles/ubuntu22.04_mlflow_server
      dockerfile: Dockerfile
    container_name: mlflow_container
    ports:
      - "5000:5000"
    expose: 
      - "5000"
    depends_on:
      - mysql
    volumes:
      - ./app_data/mlflow_tracked_data/mlruns:/mlruns

  model:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: drug_discovery
    volumes:
      - ./app_data/mlflow_tracked_data/mlruns:/app/drug_molecule_gen/mlruns
    depends_on:
      - mlflow